"""initial schema

Revision ID: 88ce4f0e2aeb
Revises: 
Create Date: 2026-03-18 15:10:37.339081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ce4f0e2aeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_openings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_posting_id', sa.String(length=36), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('seniority_level', sa.String(length=100), nullable=False),
    sa.Column('deadline_days', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('requestor_name', sa.String(length=255), nullable=False),
    sa.Column('job_description_draft', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_openings_job_posting_id'), 'job_openings', ['job_posting_id'], unique=False)
    op.create_table('selection_processes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opening_id', sa.String(length=36), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('recruiter_name', sa.String(length=255), nullable=False),
    sa.Column('recruiter_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sla_status', sa.String(length=50), nullable=False),
    sa.Column('sla_deadline_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('open_candidates_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opening_id'], ['job_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selection_processes_opening_id'), 'selection_processes', ['opening_id'], unique=False)
    op.create_index(op.f('ix_selection_processes_recruiter_id'), 'selection_processes', ['recruiter_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('days_in_stage', sa.Integer(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('screening_notes', sa.Text(), nullable=True),
    sa.Column('screening_recommendation', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['selection_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_process_id'), 'candidates', ['process_id'], unique=False)
    op.create_table('process_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['selection_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_timeline_process_id'), 'process_timeline', ['process_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('interviewer_id', sa.String(length=36), nullable=False),
    sa.Column('interview_type', sa.String(length=100), nullable=False),
    sa.Column('scheduled_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('reschedule_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['selection_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_candidate_id'), 'interviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interviews_process_id'), 'interviews', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_process_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_process_timeline_process_id'), table_name='process_timeline')
    op.drop_table('process_timeline')
    op.drop_index(op.f('ix_candidates_process_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_selection_processes_recruiter_id'), table_name='selection_processes')
    op.drop_index(op.f('ix_selection_processes_opening_id'), table_name='selection_processes')
    op.drop_table('selection_processes')
    op.drop_index(op.f('ix_job_openings_job_posting_id'), table_name='job_openings')
    op.drop_table('job_openings')
    # ### end Alembic commands ###
